[package]
name = "parser"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "parser"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.41"
fitparser = "0.10.0"
pyo3 = "0.25.0"
